version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_DOCKER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
      SECRET_KEY=secretKey: "${SECRET_KEY}"

  aplication:
    build:
      context: "vx-tel/"
    image: vx-tel-app
    env_file:
      - .env
    depends_on:
      - "db"
    volumes:
      - ./vx-tel/src:/usr/src/app/src
    ports:
      - 5000:4000
