version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network
  aplication:
    build:
      context: "vx-tel/"
    image: vx-tel-app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./vx-tel/src:/usr/src/app/src
    ports:
      - 5000:4000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge